name: Fetch items from Zotero and update Semantic Scholar library
on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * 1' # every Monday at 9:00 AM

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry --version
        poetry config virtualenvs.create false
        poetry install -vv
    - name: Run CLI
      env:
        ZOTERO_API_KEY: ${{ secrets.ZOTERO_API_KEY }}
        ZOTERO_USER_ID: ${{ secrets.ZOTERO_USER_ID }}
        SEMANTIC_SCHOLAR_LOGIN: ${{ secrets.SEMANTIC_SCHOLAR_LOGIN }}
        SEMANTIC_SCHOLAR_PASSWORD: ${{ secrets.SEMANTIC_SCHOLAR_PASSWORD }}
        SEMANTIC_SCHOLAR_API_KEY: ${{ secrets.SEMANTIC_SCHOLAR_API_KEY }}
      run: python zomantic/cli.py
